---
title: "Chapter 11"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(knitr)
###### hat values for each observation ######
Blood.Pressure <- read.csv("/cloud/project/Blood.Pressure.csv")
f.bp<-lm(Y~X,data=Blood.Pressure)
summary(f.bp)
influence.measures(f.bp)
par(mfrow=c(2,2))
plot(f.bp)
par(mfrow=c(1,1))
### Cooks distance plot####
library(olsrr)
ols_plot_cooksd_chart(f.bp)
### Standardized Residual Chart ####
ols_plot_resid_stand(f.bp)
####Studentized Residuals vs Leverage Plot ####
#Graph for detecting influential observations.
ols_plot_resid_lev(f.bp)
####Deleted Studentized Residual vs Fitted Values Plot####
#Graph for detecting outliers.
ols_plot_resid_stud_fit(f.bp)
## Nonconstant variance is detected, obs 54 is a potential leverage data point but Cooks D is small.
par(mfrow=c(1,1))
ei<-f.bp$residuals
x<-Blood.Pressure$X
plot(x,ei)
#both graphs, ei vs. X and ei vs. Yhat shows megaphoneshape. Regress abs(ei) on X given that there is only one X.
abs.ei<-abs(ei)
g<-lm(abs.ei~x)
summary(g)
si<-g$fitted.values
wi<-1/(si^2)
#WLS
f.bp1<-lm(Y~X,weights=wi,data=Blood.Pressure)
summary(f.bp1)
par(mfrow=c(2,2))
plot(f.bp1)
```
#Ridge, Lasso and Elastic Net
```{r}
#there are different libraries, for ridge and lasso, we will use glmnet and MASS
BodyFat <- read.csv("/cloud/project/BodyFat.csv")
f<-lm(Y~X1 + X2 + X3, data = BodyFat)
library(faraway)
vif(f)
#multi-collinearity exists
#first use MASS
library(MASS)
#Some experimentation was necessary to determine the appropriate range of λ. We can select the value of λ using generalized crossvalidation (GCV) which is similar to CV but is easier to compute.
rmse <- function(x,y) sqrt(mean((x-y)^2))
rgmod <- lm.ridge(Y ~ X1 + X2 + X3, data = BodyFat, lambda = seq(0,1,by=0.1))
matplot(rgmod$lambda, coef(rgmod), type="l",xlab=expression(lambda),ylab=expression(hat(beta)),col=1)
plot(rgmod) 
which.min(rgmod$GCV)
abline(v=0.1)
# λ is 0.1 
ypred <- cbind(1,as.matrix(BodyFat[,-1])) %*% coef(rgmod)[2,]
rmse(ypred, BodyFat$Y)

library(glmnet)
Y<-as.matrix(BodyFat$Y)
X<-as.matrix(BodyFat[,-c(4)])

par(mfrow=c(1,3))
fit.lasso <- glmnet(X,Y,lambda = seq(0,1,by=0.1), alpha=1)
fit.ridge <- glmnet(X,Y,lambda = seq(0,1,by=0.1),alpha=0)
fit.elnet <- glmnet(X,Y,lambda = seq(0,1,by=0.1), alpha=.5)
plot(fit.lasso, main="lasso")
plot(fit.ridge, main="ridge")
plot(fit.elnet, main="elastic")

#difficult to find the lambda#
fit.lasso1 <- cv.glmnet(X,Y, standardize=TRUE,alpha=1)
fit.ridge1 <- cv.glmnet(X,Y, standardize=TRUE,alpha=0)
fit.elnet1 <- cv.glmnet(X,Y, standardize=TRUE,alpha=.5)

#best lamda
fit.ridge1$lambda.min
fit.lasso1$lambda.min

par(mfrow=c(1,3))
plot(fit.lasso1, main="lasso")
plot(fit.ridge1, main="ridge")
plot(fit.elnet1, main="elastic")

#best values of lambda#
fit.lasso1$lambda.min
fit.ridge1$lambda.min
fit.elnet1$lambda.min

best_ridge <- glmnet(X,Y, alpha = 0, lambda = 0.4370159)
coef(best_ridge)
pred <- predict(best_ridge, s =0.4370159,newx=X)

#LASSO:#
library(lars)
lmod <- lars(X,Y)
plot(lmod)
set.seed(123)
cvlmod <- cv.lars(X,Y)
plot(cvlmod)
cvlmod$index[which.min(cvlmod$cv)]
predict(lmod,s=0.2828283,type="coef",mode="fraction")$coef
# the coefficients are shrunk somewhat from the corresponding least squares solution:#
coef(lm(Y~X1+X2+X3, BodyFat))

```

#Robust regression

```{r}
library(MASS)
summary(rr.huber <- rlm(Y~X,data=Blood.Pressure))
f.bp$coefficients
```
#Regresion Tree

```{r}
library(faraway)
#data(ozone, package = faraway)
library(rpart)
tmod<-rpart(O3~.,ozone)
tmod
#par(mfrow=c(1,2))
library(rpart.plot)
rpart.plot(tmod, digits = 3)
plot(tmod)
text(tmod)
plot(tmod,compress=T,uniform=T,branch=0.4)
text(tmod)
library(randomForest)
fmod<-randomForest(O3~.,ozone)
plot(fmod,main="")

library(C50)
data(churn)
credit_model <- C5.0(x = churnTrain[, -20], y = churnTrain$churn)
summary(credit_model)
#plot(credit_model)
credit_pred <- predict(credit_model,churnTest)
library(gmodels)
CrossTable(churnTest$churn, credit_pred,prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,dnn = c('actual default', 'predicted default'))
library(rpart.plot)
rpart.plot(tmod, digits = 3)
par(mfrow=c(1,1))

```
