---
title: "Lecture04-code"
author: "Saurabh Kulkarni"
date: "9/24/2019"
output: pdf_document
---

**Chapter 3**

**Transformations**

```{r}
PlasmaLevel = read.csv("PlasmaLevel.csv")
plot(PlasmaLevel$X, PlasmaLevel$Y)
```


```{r}
f = lm(Y~X, data=PlasmaLevel)
par(mfrow=c(2,2))
plot(f)
```

**Box-Cox**

```{r}
library(MASS)
help("boxcox")
par(mfrow=c(2,2))
boxcox(f, lambda = seq(-5,5,by=0.1))
boxcox(f, lambda = seq(-2,2,by=0.1))
boxcox(f, lambda = seq(-2,2,by=0.5))
boxcox(f, lambda = seq(-1,1,by=0.5))
```


```{r}
summary(f)
```


```{r}
f1 = lm(LogY~X, data=PlasmaLevel)
summary(f1)
```


```{r}
par(mfrow=c(2,2))
plot(f1)
```


```{r}
f2 = lm(1/sqrt(Y)~X, PlasmaLevel)
summary(f2)
```


```{r}
par(mfrow=c(2,2))
plot(f2)
```


```{r}
# Lowess regression
Dataset_1_20 = read.csv("Dataset_1_20.csv")
Dataset_1_20
f = lm(Dataset_1_20$X20~Dataset_1_20$X2)
plot(Dataset_1_20$X2, Dataset_1_20$X20, main="lowess")
abline(f, col=1)
lines(lowess(Dataset_1_20$X20~Dataset_1_20$X2, f=0.01), col=2)
lines(lowess(Dataset_1_20$X20~Dataset_1_20$X2, f=1/3), col=4)
lines(lowess(Dataset_1_20$X20~Dataset_1_20$X2, f=0.2), col=6)
lines(lowess(Dataset_1_20$X20~Dataset_1_20$X2, f=1), col=3)

```


**Chapter 4**

```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

