---
title: "Lecture03-code"
author: "Saurabh Kulkarni"
date: "9/24/2019"
output: pdf_document
---

```{r}
##Confidence Interval for Betas
toluca.reg<-lm(workhrs~lotsize,data=toluca_data)
summary(toluca.reg)
```
```{r}
confint(toluca.reg)

```


```{r}
##Confidence Interval for Yh

Xh<-data.frame(lotsize=100)

predict(toluca.reg,Xh,interval="confidence",level=0.90)

```


```{r}
##Confidence Interval for new Yh (or Prediction Interval)
predict(toluca.reg,Xh,interval="prediction",level=0.90)

```
```{r}
predict(toluca.reg,Xh,se.fit=TRUE,interval="prediction",level=0.90)

```


```{r}
MSE = 48.82331^2
VarYhat = (14.27233)^2
m = 3
var.predmean = MSE/m + VarYhat

print(var.predmean)

tc=qt(1-0.10/2,23)

cbind(419.3861-tc*sqrt(var.predmean),419.3861+tc*sqrt(var.predmean))

```


```{r}
##Working Hotelling
W <- sqrt( 2 * qf(0.90,2,23))
CI<-predict(toluca.reg,se.fit=TRUE,interval="confidence",level=0.90)
print(CI)
cbind(CI$fit[,1]-W*CI$se.fit, CI$fit[,1] + W*CI$se.fit )

```


```{r}
## F-test Example
anova(toluca.reg)
```

```{r}
F = 252378/2384
print(F)
```

```{r}
help(pf)
pf(F, 1, 23)
```

```{r}
summary(toluca.reg)
```
```{r}
t = 10.29
t^2
```

Thus, we see that there is a relation between F an t distribution, the value of $t^{2}=F$. See Chapter 2 slide 69.

```{r}
##Correlation Test
expenditures = read.csv("expenditures.csv")
cor.test(expenditures$Y1,expenditures$Y2,method="pearson")

```

```{r}
cor.test(expenditures$Y1,expenditures$Y2,method="spearman")

```

